<?= $this->doctype() ?> <!-- This Line will output the doctype we set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>  
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
	  <?= $this->headTitle() ?>
	  <?= $this->headLink()->appendStylesheet('/css/global.css') ?>
	</head> 
	<body>
		<div id="menu">
			<ul>
				<li>
					<a href="<?= $this->url(array(
			          'controller' => 'index',
			          'action' => 'index'
			        )); ?>">Accueil</a>
				</li>
				<li>
					<a href="<?= $this->url(array(
			          'controller' => 'admin',
			          'action' => 'list'
			        )); ?>">Liste</a>
		        </li>
			</ul>
		</div>
		<div id="content">
			<?php if ($this->flash(true)->has_messages()): ?>
	          <div id="flash"><?= $this->flash(); ?></div>
	        <?php endif; ?>
			<?= $this->layout()->content ?>
		</div>
		<div id="footer">
			<a href="http://github.com/o2sources/nicknames">Nicknamed</a> powered by <a href="http://www.o2sources.com">O2Sources</a>
		</div>
	</body>
</html>
